### ISSUE TITLE
Dont.

### ISSUE THREAD

**Issue by bloodball** [zebzolino/Roblox-Scripts#2]
Don't use escape sequence converters and label it as a 'obfuscator', let alone say it's yours. You can print the source to escape sequences by literally changing loadstring to print. Also, if you're going to use escape sequences then at least minify your input so newline doesn't convert into a escape sequence and take up as much space and so your variable names aren't as large.

**Comment by zebzolino** [comment]
> Don't use escape sequence converters and label it as a 'obfuscator', let alone say it's yours. You can print the source to escape sequences by literally changing loadstring to print. Also, if you're going to use escape sequences then at least minify your input so newline doesn't convert into a escape sequence and take up as much space and so your variable names aren't as large.

This isn't an issue, stop commenthing your problems.
